using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NDifference.Projects
{
	public static class ProjectBuilder
	{
		public static Project Default()
		{
			Project defaultProject = new Project
			{
				Version = "1.0",
				Settings = DefaultSettings()
			};

			return defaultProject;
		}

		public static Project FromFile(string path)
		{
			return ProjectReader.LoadFromFile(path);
		}

		public static ProjectSettings DefaultSettings()
		{
			var settings = new ProjectSettings
			{
				IndexName = "Summary",
				ConsolidateAssemblyTypes = false,
				ReportFormat = "html",
				SubFolder = "api_change",

				SummaryTitle = "API Differences Report",
				HeadingText = "This report details changes in the public API. It shows additions, modifications and removals of assemblies between the two versions. The links on this page detail which types have been added, removed or changed in each assembly.",

				OutputFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)
			};

			settings.FooterText = String.Format(CultureInfo.CurrentCulture, 
				"<div id=\"footer\"><p>Generated by <a href=\"{0}\">{1} {2}</a></p></div>",
				settings.ApplicationLink,
				settings.ApplicationName,
				settings.ApplicationVersion);

			return settings;
		}
	}
}
